# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: redcarpet

highlighter: pygments
paginate: 20 # pagination based on number of posts
paginate_path: "page/:num"

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
categories_path : categories.html
tags_path : tags.html

#BASE_PATH : http://blog.ankanbiswas.in/uno-dbyll
BASE_PATH : http://kingloveyy.github.io

description : 物尽其用！人尽其才！两全其美！
title : King的博客
logo : /avatar.jpg
#cover : /assets/images/background-cover.jpg


author:
  name: King
  maxim: Stay hungry,Stay foolish
  role: King Theme
  email: kingloveyy@vip.qq.com
  github: kingloveyy
  twitter: kingloveyy
  bio: "我是King，互相学习，互相进步"
  uno-dbyll: /avatar.jpg
